import { useEffect, useState } from 'react';
import { ArrowDownRight, ArrowRight, Check, ChevronDown, Menu, Plus, X } from 'lucide-react';
import './v2.css';

const ASSET = '/v2/assets/images/';
const cards = [
  ['Real-time fraud detection', 'Our platform combines deep financial intelligence with advanced AI to deliver real-time insights, automated risk analysis, and smarter investment decisions.'],
  ['Personalized financial AI recommendations', 'We offer a comprehensive range of innovative financial services tailored to meet your needs.'],
  ['Smart budgeting — portfolio management', 'Savings accounts that offer competitive interest rates and flexible deposit options.'],
];
const posts = ['AI and the Future of Payments of Fintech', 'The Role of AI in Fighting Financial Fraud', 'From Data to Decisions: AI in Wealth Management', 'The Rise of Conversational AI in Banking & FinTech', 'AI-Powered Risk Management: The New Standard in FinTech', 'How AI is Reshaping the Future of Financial Services'];
const questions = ['What is the difference between CAPEX and OPEX solar models?', 'How long does it take to install a solar power system?', 'Do you provide battery storage and hybrid systems?', 'What kind of EV charging stations do you install?', 'Can you help with permits and regulatory approvals?', 'What warranties and maintenance support do you provide?'];

function Reveal({ children, className = '' }: {children: React.ReactNode, className?: string}) { return <div className={`v2-reveal ${className}`}>{children}</div> }

export default function V2Page() {
  const [menu, setMenu] = useState(false); const [open, setOpen] = useState(0);
  useEffect(() => { const io = new IntersectionObserver(e => e.forEach(x => x.isIntersecting && x.target.classList.add('is-in')), { threshold: .12 }); document.querySelectorAll('.v2-reveal').forEach(x => io.observe(x)); return () => io.disconnect(); }, []);
  return <main className="v2-page">
    <header className="v2-nav"><a href="#top" className="v2-logo">Ork<span>.</span></a><nav>{['Features','Pricing','FAQ','Support'].map(x => <a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</nav><div className="v2-nav-actions"><a href="#top">Login</a><a className="v2-button small" href="#footer">Register — It’s free <ArrowDownRight size={16}/></a></div><button aria-label="Open menu" className="v2-menu" onClick={() => setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>{menu && <div className="v2-mobile-nav">{['Features','Pricing','FAQ','Support'].map(x=><a onClick={()=>setMenu(false)} key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}<a className="v2-button" href="#footer">Register — It’s free</a></div>}</header>
    <section id="top" className="v2-hero"><div className="v2-hero-copy"><Reveal><p className="v2-kicker">The future of finance is intelligent</p><h1>New Era<br/>of Banking</h1><p>Mi auctor sagittis habitasse elit. In orci lorem sodales sem enim fusce. At sem amet lacus eu aliquet venenatis.</p><a className="v2-round-link" href="#features">How Ork works <span>In 3 simple steps</span><ArrowDownRight/></a></Reveal></div><div className="v2-hero-art"><img className="v2-vertical" src={`${ASSET}vertical.avif`} alt="Financial analytics"/><img className="v2-card c1" src={`${ASSET}hero-card.avif`} alt="Dashboard"/><img className="v2-card c2" src={`${ASSET}hero-card.avif`} alt="Financial app"/><div className="v2-orb"/></div></section>
    <section className="v2-intro v2-section"><Reveal><h2>Smarter Financial Decisions,<br/>Powered by AI</h2><p>Our platform combines deep financial intelligence with advanced AI to deliver real-time insights, automated risk analysis, and smarter investment decisions. Our AI engine analyzes millions of financial data points in real time — from stock prices and market sentiment to macroeconomic trends.</p></Reveal><Reveal className="v2-phone-block"><div><h3>Built on AI.<br/>Designed for trust.</h3><p>Tailored risk levels based on real-time AI.</p></div><img src={`${ASSET}mobile-hand.avif`} alt="Mobile banking" loading="lazy"/></Reveal></section>
    <section id="features" className="v2-features v2-section"><Reveal className="v2-section-lead"><h2>Can Help You Achieve<br/>Financial Success</h2><p>Our platform combines deep financial intelligence with advanced AI to deliver real-time insights, automated risk analysis, and smarter investment decisions.</p><a href="#pricing">View More <ArrowRight size={16}/></a></Reveal><div className="v2-feature-grid">{cards.map(([title,copy],i)=><Reveal className={`v2-feature-card feature-${i}`} key={title}><div className="v2-icon">0{i+1}</div><h3>{title}</h3><p>{copy}</p>{i===0 && <img src={`${ASSET}hero-card.avif`} alt="" loading="lazy"/>}</Reveal>)}</div><Reveal className="v2-mini-grid"><div><strong>100% Dedication</strong><span>we offer a comprehensive range of innovative financial services.</span></div><div><strong>Hold money in 30+ currencies</strong><img src={`${ASSET}currencies.avif`} alt="Currencies" loading="lazy"/></div><a href="#pricing">Visit Our Services page <ArrowRight/></a></Reveal></section>
    <section className="v2-cards-showcase"><Reveal><div className="v2-stack"><img src={`${ASSET}hero-card.avif`} alt="Card"/><img src={`${ASSET}vertical.avif`} alt="Card analytics"/></div></Reveal><div className="v2-marquee"><span>INVEST. SAVE. THRIVE. • INVEST. SAVE. THRIVE. • INVEST. SAVE. THRIVE. •</span></div><p>Artificial Intelligence is revolutionizing the fintech industry by enabling smarter decision-making, personalized financial services, and enhanced risk management. From fraud detection and credit scoring to automated trading and customer support, AI-powered solutions are driving efficiency, accuracy, and innovation.</p></section>
    <section className="v2-stats">{[['0 K+','Total Transaction processed through our platform'],['0 %','Fraud Detection Accuracy using AI-powered monitoring'],['0 +','Users Trust Us across 12+ countries'],['0 +','Total Transaction Volume processed through our platform']].map(([n,t])=><Reveal key={t}><strong>{n}</strong><span>{t}</span></Reveal>)}</section>
    <section className="v2-testimonials v2-section"><Reveal className="v2-section-lead"><h2>Can Help You Achieve<br/>Financial Success</h2><p>Our platform combines deep financial intelligence with advanced AI to deliver real-time insights, automated risk analysis, and smarter investment decisions.</p><a href="#blog">View More <ArrowRight size={16}/></a></Reveal><Reveal className="v2-quote"><span>“</span><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat.</p><strong>Lorem Ipsum</strong><small>Project Manager at lore ipsum</small></Reveal></section>
    <section id="blog" className="v2-blog v2-section"><Reveal><h2>From Our Blog</h2><p>Discover in-depth insights at the intersection of finance and technology, helping you understand how AI is transforming the way we invest and grow wealth.</p></Reveal><div>{posts.map((p,i)=><Reveal className="v2-post" key={p}><span>0{i+1}</span><h3>{p}</h3><p>{i<3?'How artificial intelligence is powering faster transactions, improving security, and shaping the next':'From smarter credit scoring to fraud detection and personalized banking, discover...'}</p><a href="#footer">Learn more <ArrowRight/></a></Reveal>)}</div></section>
    <section id="pricing" className="v2-pricing v2-section"><Reveal><h2>Pricing Plans</h2><p>Our platform combines deep financial intelligence with advanced AI to deliver real-time insights, automated risk analysis, and smarter investment decisions.</p></Reveal><div className="v2-price-grid">{[['Basic plan','$9.00/mo'],['Standard plan','$29.00/mo'],['Executive plan','$229.00/mo']].map(([p,price],i)=><Reveal className="v2-price" key={p}><div className="v2-icon">0{i+1}</div><h3>{p}</h3><p>Elementum dui nulla sollicitudin ut etiam euisque vestibulum non.</p><strong>{price}</strong><a className="v2-button" href="#footer">Choose plan <ArrowDownRight size={16}/></a></Reveal>)}</div></section>
    <section id="faq" className="v2-faq v2-section"><Reveal><h2>Need Help?<br/>We’re here to assist.</h2><p>Still have questions? Feel free to contact our Support team</p><a className="v2-button" href="#footer">Book a Call <ArrowDownRight size={16}/></a></Reveal><div>{questions.map((q,i)=><div className="v2-question" key={q}><button aria-expanded={open===i} onClick={()=>setOpen(open===i?-1:i)}><span>0{i+1}.</span>{q}<Plus className={open===i?'rot':''}/></button>{open===i&&<p>In the CAPEX model, the client owns the system outright by paying upfront. In the OPEX model, the system is installed with no upfront investment, and the client pays a monthly fee for the energy produced.</p>}</div>)}</div></section>
    <section className="v2-newsletter"><img src={`${ASSET}ai-bg.avif`} alt=""/><Reveal><h2>Can Help You Achieve<br/>Financial Success</h2><p>Our platform combines deep financial intelligence with advanced AI to deliver real-time insights, automated risk analysis, and smarter investment decisions.</p><form onSubmit={e=>e.preventDefault()}><label className="sr-only" htmlFor="v2email">Your email</label><input id="v2email" type="email" placeholder="Your email address"/><button className="v2-button">Book a Call <ArrowDownRight size={16}/></button></form></Reveal></section>
    <footer id="footer" className="v2-footer"><div><a className="v2-logo" href="#top">Ork<span>.</span></a><p>Building the future of thoughtful finance.</p></div><div><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a><a href="#blog">Blog</a></div><div><a href="tel:+18919891191">+1 891 989-11-91</a><a href="mailto:hello@ork.com">hello@Ork.com</a></div><small>© 2025 — Copyright</small></footer>
  </main>;
}
